// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	blog "github.com/tiptok/gz-blog-microsevices/app/blog/cmd/api/internal/handler/blog"
	"github.com/tiptok/gz-blog-microsevices/app/blog/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/sign-up",
				Handler: blog.SignUpHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/sign-in",
				Handler: blog.SignInHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/posts",
				Handler: blog.CreatePostsHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts/:id",
				Handler: blog.GetPostHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/posts/:id",
				Handler: blog.DeletePostHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/posts/:id",
				Handler: blog.UpdatePostHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/posts",
				Handler: blog.ListPostsHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/comments/:id",
				Handler: blog.DeleteCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/comments",
				Handler: blog.CreateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/comments/:id",
				Handler: blog.UpdateCommentHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/comments",
				Handler: blog.ListCommentsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api.rest.blog.v1"),
	)
}
