# kind: ConfigMap
# apiVersion: v1
# metadata:
#   name: gz-blog-user-config
# data:
#   user.yaml: |-
    
#     Name: user.rpc
#     ListenOn: 0.0.0.0:8080
#     Log:
#       ServiceName: user-rpc
#       Level: info

#     Redis:
#       Host: service-redis.redis.svc.cluster.local:6379
#       Type: node
#       Pass:
#     DB:
#       DataSource: root:password@tcp(mysql-svc.app.svc.cluster.local:3306)/blog?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
#     Cache:
#       - Host: service-redis.redis.svc.cluster.local:6379
#         Pass:
        
# 使用etcd负载
kind: ConfigMap
apiVersion: v1
metadata:
  name: gz-blog-user-config
data:
  user.yaml: |-
    
    Name: user.rpc
    ListenOn: 0.0.0.0:8080
    Etcd:
      Hosts:
        - etcd.etcd.svc.cluster.local:2379
      Key: user.rpc
    Log:
      ServiceName: user-rpc
      Level: info

    Redis:
      Host: service-redis.redis.svc.cluster.local:6379
      Type: node
      Pass:
    DB:
      DataSource: root:password@tcp(mysql-svc.app.svc.cluster.local:3306)/blog?charset=utf8mb4&parseTime=true&loc=Asia%2FShanghai
    Cache:
      - Host: service-redis.redis.svc.cluster.local:6379
        Pass:      