apiVersion: apps/v1
kind: Deployment
metadata:
  name: gz-blog
  labels:
    app: gz-blog
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: gz-blog
  template:
    metadata:
      labels:
        app: gz-blog
    spec:
      containers:
      - name: gz-blog
        image: docker.io/tiptok/gz-blog:1.0.0
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["sh","-c","sleep 5"]
        ports:
        - containerPort: 8080
        # readinessProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 10
        # livenessProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 20
        # resources:
        #   requests:
        #     cpu: 500m
        #     memory: 512Mi
        #   limits:
        #     cpu: 1000m
        #     memory: 1024Mi
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: config
          mountPath: /app/etc 
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
        - name: config
          configMap:
            name: gz-blog-config
---

apiVersion: v1
kind: Service
metadata:
  name: gz-blog-svc
spec:
  ports:
    - port: 8080
  selector:
    app: gz-blog

---

# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: gz-blog-hpa-c
#   namespace: default
#   labels:
#     app: gz-blog-hpa-c
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: gz-blog
#   minReplicas: 3
#   maxReplicas: 10
#   metrics:
#   - type: Resource
#     resource:
#       name: cpu
#       targetAverageUtilization: 80

# ---

# apiVersion: autoscaling/v2beta1
# kind: HorizontalPodAutoscaler
# metadata:
#   name: gz-blog-hpa-m
#   namespace: default
#   labels:
#     app: gz-blog-hpa-m
# spec:
#   scaleTargetRef:
#     apiVersion: apps/v1
#     kind: Deployment
#     name: gz-blog
#   minReplicas: 3
#   maxReplicas: 10
#   metrics:
#   - type: Resource
#     resource:
#       name: memory
#       targetAverageUtilization: 80
