// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	Code string `json:"code"`
}

type LoginResponse struct {
	Token string `json:"token"`
}

type UserInfoRequest struct {
}

type UserInfoResponse struct {
	User User `json:"user"`
}

type ShopListRequest struct {
	Page int `json:"page"`
	Size int `json:"size"`
}

type ShopListResponse struct {
	Shops []Shop `json:"shops"`
	Total int    `json:"total"`
}

type User struct {
}

type Shop struct {
	ShopId       int     `json:"shopId"`
	Name         string  `json:"name"`
	Introduction string  `json:"introduction"`
	Address      string  `json:"address"`
	Lon          float64 `json:"lon"`
	Lat          float64 `json:"lat"`
	Rank         int     `json:"rank"`
}

type Coach struct {
	CoachId         int      `json:"coachId"`
	ShopId          int      `json:"shopId"`
	Name            string   `json:"name"`
	JobTitle        string   `json:"jobTitle"`
	Labels          []string `json:"labels"`
	TotalLessonTime int      `json:"totalLessonTime"`
	Rank            int      `json:"rank"`
}

type CoachListRequest struct {
	ShopId int `json:"shopId"`
}

type CoachListResponse struct {
	Coaches []Coach `json:"coach"`
	Total   int     `json:"total"`
}

type CoachReserveRequest struct {
	CoachId       int    `json:"coachId"`
	TimeSpanBegin string `json:"timeSpanBegin"`
	TimeSpanEnd   string `json:"timeSpanEnd"`
}

type CoachReserveResponse struct {
}
