// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/protobuf/user/v1/user.proto

/*
Package v1 is a generated protocol buffer package.

It is generated from these files:

	api/protobuf/user/v1/user.proto

It has these top-level messages:

	User
	ListUsersByIDsRequest
	ListUsersByIDsResponse
	GetUserRequest
	GetUserResponse
	GetUserByEmailRequest
	GetUserByUsernameRequest
	CreateUserRequest
	CreateUserResponse
	UpdateUserRequest
	UpdateUserResponse
	DeleteUserRequest
	DeleteUserResponse
*/
package v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	Id       uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Uuid     string `protobuf:"bytes,2,opt,name=uuid" json:"uuid,omitempty"`
	Username string `protobuf:"bytes,3,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,4,opt,name=email" json:"email,omitempty"`
	Avatar   string `protobuf:"bytes,5,opt,name=avatar" json:"avatar,omitempty"`
	Password string `protobuf:"bytes,6,opt,name=password" json:"password,omitempty"`
}

func (m *User) Reset()                    { *m = User{} }
func (m *User) String() string            { return proto.CompactTextString(m) }
func (*User) ProtoMessage()               {}
func (*User) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *User) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *User) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetAvatar() string {
	if m != nil {
		return m.Avatar
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ListUsersByIDsRequest struct {
	Ids []uint64 `protobuf:"varint,1,rep,packed,name=ids" json:"ids,omitempty"`
}

func (m *ListUsersByIDsRequest) Reset()                    { *m = ListUsersByIDsRequest{} }
func (m *ListUsersByIDsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListUsersByIDsRequest) ProtoMessage()               {}
func (*ListUsersByIDsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListUsersByIDsRequest) GetIds() []uint64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type ListUsersByIDsResponse struct {
	Users []*User `protobuf:"bytes,1,rep,name=users" json:"users,omitempty"`
}

func (m *ListUsersByIDsResponse) Reset()                    { *m = ListUsersByIDsResponse{} }
func (m *ListUsersByIDsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListUsersByIDsResponse) ProtoMessage()               {}
func (*ListUsersByIDsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListUsersByIDsResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

type GetUserRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type GetUserByEmailRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *GetUserByEmailRequest) Reset()                    { *m = GetUserByEmailRequest{} }
func (m *GetUserByEmailRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserByEmailRequest) ProtoMessage()               {}
func (*GetUserByEmailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetUserByEmailRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *GetUserByEmailRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type GetUserByUsernameRequest struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *GetUserByUsernameRequest) Reset()                    { *m = GetUserByUsernameRequest{} }
func (m *GetUserByUsernameRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserByUsernameRequest) ProtoMessage()               {}
func (*GetUserByUsernameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetUserByUsernameRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *GetUserByUsernameRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateUserRequest) Reset()                    { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()               {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type CreateUserResponse struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *CreateUserResponse) Reset()                    { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()               {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *CreateUserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserRequest struct {
	User *User `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *UpdateUserRequest) Reset()                    { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()               {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

type UpdateUserResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *UpdateUserResponse) Reset()                    { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()               {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UpdateUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type DeleteUserRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteUserRequest) Reset()                    { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()               {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *DeleteUserRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserResponse struct {
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
}

func (m *DeleteUserResponse) Reset()                    { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()               {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *DeleteUserResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func init() {
	proto.RegisterType((*User)(nil), "api.protobuf.user.v1.User")
	proto.RegisterType((*ListUsersByIDsRequest)(nil), "api.protobuf.user.v1.ListUsersByIDsRequest")
	proto.RegisterType((*ListUsersByIDsResponse)(nil), "api.protobuf.user.v1.ListUsersByIDsResponse")
	proto.RegisterType((*GetUserRequest)(nil), "api.protobuf.user.v1.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "api.protobuf.user.v1.GetUserResponse")
	proto.RegisterType((*GetUserByEmailRequest)(nil), "api.protobuf.user.v1.GetUserByEmailRequest")
	proto.RegisterType((*GetUserByUsernameRequest)(nil), "api.protobuf.user.v1.GetUserByUsernameRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "api.protobuf.user.v1.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "api.protobuf.user.v1.CreateUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "api.protobuf.user.v1.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "api.protobuf.user.v1.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "api.protobuf.user.v1.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "api.protobuf.user.v1.DeleteUserResponse")
}

func init() { proto.RegisterFile("api/protobuf/user/v1/user.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 504 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xed, 0x8e, 0x12, 0x31,
	0x14, 0xdd, 0x81, 0x81, 0x5d, 0xef, 0x26, 0x28, 0x37, 0xbb, 0xa4, 0x99, 0x3f, 0x92, 0xaa, 0x11,
	0xa3, 0x29, 0xee, 0xfa, 0x04, 0x02, 0xc6, 0xac, 0xf1, 0xd7, 0x18, 0x12, 0xe3, 0xbf, 0x2e, 0xd3,
	0x4d, 0x9a, 0xc0, 0x32, 0x4e, 0x67, 0x30, 0xfb, 0x16, 0xbe, 0x9c, 0xef, 0x63, 0xda, 0xf9, 0xa0,
	0xcc, 0x07, 0xa0, 0xfb, 0x8b, 0xb9, 0xed, 0xb9, 0xe7, 0xdc, 0x9e, 0x9e, 0x06, 0x78, 0xce, 0x43,
	0x39, 0x0e, 0xa3, 0x75, 0xbc, 0xbe, 0x4d, 0xee, 0xc6, 0x89, 0x12, 0xd1, 0x78, 0x73, 0x65, 0x7e,
	0x99, 0x59, 0xc5, 0x0b, 0x1e, 0x4a, 0x96, 0x03, 0x98, 0xd9, 0xd8, 0x5c, 0xd1, 0xdf, 0x0e, 0xb8,
	0x73, 0x25, 0x22, 0xec, 0x41, 0x4b, 0x06, 0xc4, 0x19, 0x3a, 0x23, 0xd7, 0x6f, 0xc9, 0x00, 0x11,
	0xdc, 0x24, 0x91, 0x01, 0x69, 0x0d, 0x9d, 0xd1, 0x13, 0xdf, 0x7c, 0xa3, 0x07, 0x67, 0xba, 0xef,
	0x9e, 0xaf, 0x04, 0x69, 0x9b, 0xf5, 0xa2, 0xc6, 0x0b, 0xe8, 0x88, 0x15, 0x97, 0x4b, 0xe2, 0x9a,
	0x8d, 0xb4, 0xc0, 0x01, 0x74, 0xf9, 0x86, 0xc7, 0x3c, 0x22, 0x1d, 0xb3, 0x9c, 0x55, 0x9a, 0x29,
	0xe4, 0x4a, 0xfd, 0x5a, 0x47, 0x01, 0xe9, 0xa6, 0x4c, 0x79, 0x4d, 0xdf, 0xc0, 0xe5, 0x57, 0xa9,
	0x62, 0x3d, 0x95, 0x9a, 0x3c, 0xdc, 0xcc, 0x94, 0x2f, 0x7e, 0x26, 0x42, 0xc5, 0xf8, 0x0c, 0xda,
	0x32, 0x50, 0xc4, 0x19, 0xb6, 0x47, 0xae, 0xaf, 0x3f, 0xe9, 0x17, 0x18, 0x94, 0xa1, 0x2a, 0x5c,
	0xdf, 0x2b, 0x81, 0xef, 0xa1, 0xa3, 0x47, 0x4b, 0xd1, 0xe7, 0xd7, 0x1e, 0xab, 0x3b, 0x3d, 0xd3,
	0x8d, 0x7e, 0x0a, 0xa4, 0x43, 0xe8, 0x7d, 0x16, 0x86, 0x2a, 0xd7, 0x2b, 0x59, 0x42, 0x3f, 0xc2,
	0xd3, 0x02, 0x91, 0xc9, 0x30, 0x70, 0x75, 0xb7, 0x01, 0xed, 0x57, 0x31, 0x38, 0x7a, 0x03, 0x97,
	0x19, 0xc5, 0xe4, 0xe1, 0x93, 0x76, 0x28, 0xd7, 0x2a, 0xec, 0x73, 0x6c, 0xfb, 0x6c, 0x9b, 0x5a,
	0x25, 0x9b, 0x7c, 0x20, 0x05, 0xd5, 0x3c, 0xbb, 0x85, 0x9c, 0xcd, 0xbe, 0x28, 0xa7, 0x74, 0x51,
	0xfb, 0x38, 0xa7, 0xd0, 0x9f, 0x46, 0x82, 0xc7, 0xc2, 0xb6, 0xe1, 0x5f, 0xcf, 0x38, 0x03, 0xb4,
	0x49, 0xfe, 0xd3, 0xa9, 0x29, 0xf4, 0xe7, 0x61, 0xf0, 0xc8, 0x51, 0x18, 0xa0, 0x4d, 0x92, 0x8d,
	0x42, 0xe0, 0x54, 0x25, 0x8b, 0x85, 0x50, 0xca, 0x10, 0x9d, 0xf9, 0x79, 0x49, 0x5f, 0x40, 0x7f,
	0x26, 0x96, 0x62, 0x57, 0xb4, 0x1c, 0x03, 0x06, 0x68, 0x83, 0x0e, 0x91, 0x5e, 0xff, 0xe9, 0xc0,
	0xb9, 0x86, 0x7e, 0x13, 0xd1, 0x46, 0x2e, 0x04, 0xae, 0xa0, 0xb7, 0x1b, 0x5a, 0x7c, 0x5b, 0x7f,
	0x90, 0xda, 0x57, 0xe0, 0xbd, 0x3b, 0x0e, 0x9c, 0x8e, 0x45, 0x4f, 0xf0, 0x3b, 0x9c, 0x66, 0x39,
	0xc1, 0x97, 0xf5, 0xad, 0xbb, 0xb1, 0xf7, 0x5e, 0x1d, 0x40, 0x15, 0xcc, 0x77, 0xc5, 0x8b, 0xc9,
	0xc2, 0xdc, 0x74, 0x90, 0xda, 0xc8, 0x1f, 0xaf, 0xb3, 0x84, 0x7e, 0x25, 0xe9, 0xc8, 0x0e, 0x48,
	0x95, 0x9e, 0xc4, 0xf1, 0x6a, 0x1c, 0x60, 0x1b, 0x5f, 0x7c, 0x5d, 0xdf, 0x56, 0x79, 0x25, 0xde,
	0xe8, 0x30, 0xd0, 0x96, 0xd8, 0xc6, 0xb2, 0x49, 0xa2, 0x92, 0xfe, 0x26, 0x89, 0x6a, 0xc2, 0x53,
	0x89, 0x6d, 0x48, 0x9b, 0x24, 0x2a, 0x59, 0x6f, 0x92, 0xa8, 0xe6, 0x9d, 0x9e, 0x4c, 0xc8, 0x8f,
	0x01, 0x1b, 0xd7, 0xfd, 0xeb, 0xdc, 0x76, 0xcd, 0xca, 0x87, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x31, 0x8a, 0xb0, 0x65, 0x94, 0x06, 0x00, 0x00,
}
