// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	skateboard "github.com/tiptok/gz-blog-microsevices/app/skateboard/cmd/mini/internal/handler/skateboard"
	"github.com/tiptok/gz-blog-microsevices/app/skateboard/cmd/mini/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/mini/login",
				Handler: skateboard.MiniLoginHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mini/user-info",
				Handler: skateboard.MiniUserInfoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mini/shop-list",
				Handler: skateboard.MiniShopListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mini/coach-list",
				Handler: skateboard.MiniShopCoachListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/mini/coach-reserve",
				Handler: skateboard.MiniCoachReserveHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/coach",
				Handler: skateboard.SystemCoachCreateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/shop/:id",
				Handler: skateboard.SystemShopGetHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/shop",
				Handler: skateboard.SystemShopSaveHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/system/shop/:id",
				Handler: skateboard.SystemShopDeleteHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/system/shop/:id",
				Handler: skateboard.SystemShopUpdateHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/system/shop/search",
				Handler: skateboard.SystemShopSearchHandler(serverCtx),
			},
		},
		rest.WithPrefix("/skateboard"),
	)
}
