apiVersion: v1
kind: Namespace
metadata:
  name: etcd
  labels:
    app.kubernetes.io/name: etcd
    app.kubernetes.io/instance: etcd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: etcd
  namespace: etcd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: etcd
  template:
    metadata:
      labels:
        app: etcd
    spec:
      containers:
      - name: gateway
        image: quay.io/coreos/etcd:v3.4.16
        imagePullPolicy: IfNotPresent
        env:
        # - name: ETCDCTL_API
        #   value: "3"
        #   value: "http://localhost:2379"
        - name: ETCD_LISTEN_CLIENT_URLS
          value: "http://0.0.0.0:2379"
        - name: ETCD_ADVERTISE_CLIENT_URLS 
          value: "http://0.0.0.0:2379" 
        ports:
        - containerPort: 2379
          protocol: TCP
          name: tcp01
        - containerPort: 2380
          protocol: TCP
          name: tcp02
        volumeMounts:
        - mountPath: /etcd
          name: etcd-etcd
        - mountPath: /etcd-server.etcd
          name: etcd-data
      volumes:
      - name: etcd-etcd
        emptyDir: {}
        # persistentVolumeClaim:
        #   claimName: etcd-etcd
      - name: etcd-data
        emptyDir: {}
        # persistentVolumeClaim:
        #   claimName: etcd-data
---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#  name: etcd-etcd
#  namespace: etcd
# spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 10Gi
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#  name: etcd-data
#  namespace: etcd
# spec:
#  accessModes:
#    - ReadWriteMany
#  resources:
#    requests:
#      storage: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: etcd
  namespace: etcd
  labels:
    name: etcd
spec:
  ports:
  - name: etcd-01
    protocol: TCP
    targetPort: 2379
    port: 2379
  - name: etcd-02
    protocol: TCP
    targetPort: 2380
    port: 2380
  selector:
    app: etcd

---
apiVersion: v1
kind: Service
metadata:
  name: etcd-client
  namespace: etcd
spec:
  ports:
    - name: http
      nodePort: 30453
      port: 2379
      targetPort: 2379
      protocol: TCP
  type: NodePort
  selector:
    app: etcd    