Name: blog.rpc
ListenOn: 127.0.0.1:8080
Etcd:
  Hosts:
  - etcd-client.etcd:2379
  Key: blog.rpc
Http:
  Port: '0.0.0.0:9080'

UserRpc:
  Etcd:
    Hosts:
      - etcd-client.etcd:2379
    Key: user.rpc
