// Code generated by goctl. DO NOT EDIT!
// Source: product.proto

package server

import (
	"context"

	"github.com/tiptok/gz-blog-microsevices/api/protobuf/product/v1"
	"github.com/tiptok/gz-blog-microsevices/app/product/cmd/rpc/internal/logic"
	"github.com/tiptok/gz-blog-microsevices/app/product/cmd/rpc/internal/svc"
)

type ProductServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedProductServiceServer
}

func NewProductServiceServer(svcCtx *svc.ServiceContext) *ProductServiceServer {
	return &ProductServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServiceServer) GetProduct(ctx context.Context, in *v1.GetProductRequest) (*v1.GetProductResponse, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}

func (s *ProductServiceServer) CreateProduct(ctx context.Context, in *v1.CreateProductRequest) (*v1.CreateProductResponse, error) {
	l := logic.NewCreateProductLogic(ctx, s.svcCtx)
	return l.CreateProduct(in)
}

func (s *ProductServiceServer) UpdateProduct(ctx context.Context, in *v1.UpdateProductRequest) (*v1.UpdateProductResponse, error) {
	l := logic.NewUpdateProductLogic(ctx, s.svcCtx)
	return l.UpdateProduct(in)
}

func (s *ProductServiceServer) DeleteProduct(ctx context.Context, in *v1.DeleteProductRequest) (*v1.DeleteProductResponse, error) {
	l := logic.NewDeleteProductLogic(ctx, s.svcCtx)
	return l.DeleteProduct(in)
}

func (s *ProductServiceServer) ListProducts(ctx context.Context, in *v1.ListProductsRequest) (*v1.ListProductsResponse, error) {
	l := logic.NewListProductsLogic(ctx, s.svcCtx)
	return l.ListProducts(in)
}
