// Code generated by goctl. DO NOT EDIT!
// Source: auth.proto

package server

import (
	"context"

	"github.com/tiptok/gz-blog-microsevices/api/protobuf/auth/v1"
	"github.com/tiptok/gz-blog-microsevices/app/auth/cmd/rpc/internal/logic"
	"github.com/tiptok/gz-blog-microsevices/app/auth/cmd/rpc/internal/svc"
)

type AuthServiceServer struct {
	svcCtx *svc.ServiceContext
	v1.UnimplementedAuthServiceServer
}

func NewAuthServiceServer(svcCtx *svc.ServiceContext) *AuthServiceServer {
	return &AuthServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AuthServiceServer) GenerateToken(ctx context.Context, in *v1.GenerateTokenRequest) (*v1.GenerateTokenResponse, error) {
	l := logic.NewGenerateTokenLogic(ctx, s.svcCtx)
	return l.GenerateToken(in)
}

func (s *AuthServiceServer) ValidateToken(ctx context.Context, in *v1.ValidateTokenRequest) (*v1.ValidateTokenResponse, error) {
	l := logic.NewValidateTokenLogic(ctx, s.svcCtx)
	return l.ValidateToken(in)
}

func (s *AuthServiceServer) RefreshToken(ctx context.Context, in *v1.RefreshTokenRequest) (*v1.RefreshTokenResponse, error) {
	l := logic.NewRefreshTokenLogic(ctx, s.svcCtx)
	return l.RefreshToken(in)
}
